#!/usr/bin/env php
<?php
//
// Copyright (c) 2013, Zynga Inc.
// https://github.com/zynga/saigon
// Author: Matt West (https://github.com/mhwest13)
// License: BSD 2-Clause
//

/**
 * Fetch Router VMs
 *      Script used to query Cloud.com for the list of RouterVMs in the 
 *      datacenters. It then writes it into the Redis store, that way we
 *      can call into Saigon and receiving the results immediately.
 */

/* Requires for includes of functions and definitions */
require_once dirname(dirname(__FILE__)).'/conf/saigon.inc.php';
/* Load up Module Autoloader Class File */
require_once BASE_PATH.'/lib/classLoader.class.php';
Saigon_ClassLoader::register();
/* Load up Datacenter Info */
$datacenters = parse_ini_file(BASE_PATH.'/conf/cdc_creds.ini', true);
$results = array();
$zones = array();
foreach ($datacenters as $datacenter => $dccreds) {
    $cdcrvm = new CDC_RVM($dccreds);
    $data = $cdcrvm->fetchData();
    foreach ($data->listroutersresponse->router as $key => $dataObj) {
        if ($dataObj->state != 'Running') {
            continue;
        }
        $zone = preg_split("/-/", $dataObj->zonename);
        if (!in_array($zone[0], $zones)) {
            array_push($zones, $zone[0]);
        }
        $results[$zone[0]][$dataObj->name]['parent'] = $dataObj->hostname;
        $results[$zone[0]][$dataObj->name]['ipaddress'] = $dataObj->guestipaddress;
    }
}
CDC_DS::init();
foreach ($results as $zone => $zoneinfo) {
    print $zone."\n";
    CDC_DS::writeRouterInfo($zone, json_encode($zoneinfo));
}
CDC_DS::writeRouterZones($zones);

