#!/usr/bin/env php
<?php
//
// Copyright (c) 2014, Zynga Inc.
// https://github.com/zynga/saigon
// Author: Matt West (https://github.com/mhwest13)
// License: BSD 2-Clause
//

/**
 *  Host Audit
 *      Consumer / Async Job Initiator for finding hosts which aren't being monitored
 */

/* Requires for includes of functions and definitions */
require_once dirname(dirname(__FILE__)).'/conf/saigon.inc.php';
// Lets load up the composer autoloader
require_once BASE_PATH. '/vendor/autoload.php';
// Lets load up the saigon autoloader
require_once BASE_PATH.'/lib/classLoader.class.php';
Saigon_ClassLoader::register();

declare(ticks = 1);

/**
 * sighandler
 * 
 * @param mixed $signal signal being passed in
 *
 * @access public
 * @return void
 */
function sighandler($signal)
{
    global $run;
    echo "Caught signal $signal, exiting gracefully...\n";
    $run = false;
    sleep(1);
    exit(0);
}

/**
 * Envoke Signal Handling function
 */
$run = true;
pcntl_signal(SIGTERM, "sighandler");
pcntl_signal(SIGQUIT, "sighandler");
pcntl_signal(SIGINT, "sighandler");
pcntl_signal(SIGQUIT, "sighandler");
pcntl_signal(SIGABRT, "sighandler");
/**
 * Initialize Beanstalkd Connection
 */
NagPhean::init(BEANSTALKD_SERVER, BEANSTALKD_TUBE, true);
/**
 * Lets make the jobs for the saigon-tester consumer to run
 */
$deployments = RevDeploy::getDeployments();
$commonRepos = RevDeploy::getCommonRepos();
$buildRepos = array_diff($deployments, $commonRepos);
if (!empty($buildRepos)) {
    foreach($buildRepos as $key => $deployment) {
        NagPhean::addJob(
            BEANSTALKD_TUBE,
            json_encode(
                array(
                    'deployment' => $deployment,
                    'type' => 'hostaudit'
                )
            ),
            2048, 0, 900
        );
    }
}
