#!/usr/bin/env php
<?php
//
// Copyright (c) 2013, Zynga Inc.
// https://github.com/zynga/saigon
// Author: Matt West (https://github.com/mhwest13)
// License: BSD 2-Clause
//

/**
 *  Nagios Tester
 *      Consumer / Async Job Executor for Diff / Show / Test Config Jobs
 */

/* Requires for includes of functions and definitions */
require_once dirname(dirname(__FILE__)).'/conf/saigon-tester.inc.php';
// Lets load up the composer autoloader
require_once BASE_PATH. '/vendor/autoload.php';
// Lets load up the saigon autoloader
require_once BASE_PATH.'/lib/classLoader.class.php';
Saigon_ClassLoader::register();

declare(ticks = 1);

/**
 * sighandler
 * 
 * @param mixed $signal signal being passed in
 *
 * @access public
 * @return void
 */
function sighandler($signal)
{
    global $run;
    echo "Caught signal $signal, exiting gracefully...\n";
    $run = false;
    sleep(1);
    exit(0);
}

/**
 * testBuild 
 * 
 * @param mixed $deployment    deployment we are building for test purposes
 * @param mixed $revision      revision we are building for test purposes
 *
 * @access public
 * @return void
 */
function testBuild($deployment, $revision, $shardposition)
{
    $starttime = time();
    $buildReturn = NagCreate::buildDeployment($deployment, $revision, false, true, $shardposition);
    if ($buildReturn !== true) {
        $buildOutput['starttime'] = $starttime;
        $buildOutput['timestamp'] = time();
        $buildOutput['output'] = base64_encode($buildReturn);
        $buildOutput['exitcode'] = 1;
        RevDeploy::setConsumerDeploymentInfo($deployment, $revision, 'test', $buildOutput);
        unset($buildOutput, $buildReturn);
    }
    else {
        $testReturn = NagCreate::testDeployment($deployment);
        $testReturn['starttime'] = $starttime;
        $testReturn['timestamp'] = time();
        $testReturn['output'] = base64_encode(implode("\n", $testReturn['output']));
        RevDeploy::setConsumerDeploymentInfo($deployment, $revision, 'test', $testReturn);
        unset($testReturn, $buildReturn);
    }
    unset($starttime);
    return;
}

/**
 * showBuild 
 * 
 * @param mixed $deployment    deployment we are building configs for
 * @param mixed $revision      revision of configs we are building
 *
 * @access public
 * @return void
 */
function showBuild($deployment, $revision, $shardposition = false)
{
    $starttime = time();
    $buildReturn = NagCreate::buildDeployment($deployment, $revision, false, true, $shardposition);
    if ($buildReturn !== true) {
        $buildOutput['starttime'] = $starttime;
        $buildOutput['timestamp'] = time();
        $buildOutput['output'] = $buildReturn;
        $buildOutput['exitcode'] = 1;
        RevDeploy::setConsumerDeploymentInfo($deployment, $revision, 'build', $buildOutput);
        unset($buildOutput, $buildReturn);
    }
    else {
        $configOutput['configs'] = json_encode(NagCreate::returnDeploymentConfigs($deployment));
        $configOutput['starttime'] = $starttime;
        $configOutput['timestamp'] = time();
        $configOutput['exitcode'] = 0;
        RevDeploy::setConsumerDeploymentInfo($deployment, $revision, 'build', $configOutput);
        unset($configOutput, $buildReturn);
    }
    unset($starttime);
    return;
}

/**
 * diffBuild 
 * 
 * @param mixed $deployment    deployment we are diffing
 * @param mixed $fromrev       from revision we are diffing
 * @param mixed $torev         to revision we are diffing
 *
 * @access public
 * @return void
 */
function diffBuild($deployment, $fromrev, $torev, $shardposition = false)
{
    $results = array();
    $starttime = time();
    $return = NagDiff::buildDiffRevisions($deployment, $fromrev, $torev, $shardposition);
    if ($return === false) {
        $results['output'] = base64_encode(NagDiff::getOutput());
        $results['starttime'] = $starttime;
        $results['timestamp'] = time();
        $results['fromrev'] = $fromrev;
        $results['torev'] = $torev;
        $results['status'] = 'failed';
        RevDeploy::setConsumerDeploymentInfo($deployment, false, 'diff', $results);
    }
    else {
        $results['configs'] = json_encode(NagDiff::getResults());
        $results['starttime'] = $starttime;
        $results['timestamp'] = time();
        $results['fromrev'] = $fromrev;
        $results['torev'] = $torev;
        $results['status'] = 'success';
        RevDeploy::setConsumerDeploymentInfo($deployment, false, 'diff', $results);
    }
    unset($starttime, $results, $return);
}

/**
 * hostaudit
 *
 * @param mixed $deployment deployment we are checking for host and service warnings
 *
 * @access public
 * @return void
 */
function hostaudit($deployment)
{
    $revision = RevDeploy::getDeploymentRev($deployment);
    $buildReturn = NagCreate::buildDeployment($deployment, $revision, false, true, false);
    if ($buildReturn !== true) {
        $naglogger = new NagLogger();
        $naglogger->addToLog("Unable to properly build deployment: $deployment :: reason: $buildReturn");
        unset($buildReturn);
    }
    else {
        $testReturn = NagCreate::testDeployment($deployment);
        $results = array();
        $results['last_updated'] = time();
        $results['hosts_without_services'] = array();
        $results['hosts_without_services']['count'] = 0;
        $results['hosts_without_services']['hosts'] = array();
        $results['hosts_without_contacts'] = array();
        $results['hosts_without_contacts']['count'] = 0;
        $results['hosts_without_contacts']['hosts'] = array();
        $results['services_without_contacts'] = array();
        $results['services_without_contacts']['count'] = 0;
        foreach ($testReturn['output'] as $index => $line) {
            if (preg_match("/Warning: Host '(.+)' has no services associated with it!/", $line, $matches)) {
                ++$results['hosts_without_services']['count'];
                array_push($results['hosts_without_services']['hosts'], $matches[1]);
            }
            elseif (preg_match("/Warning: Host '(.+)' has no default contacts or contactgroups defined!/", $line, $matches)) {
                ++$results['hosts_without_contacts']['count'];
                array_push($results['hosts_without_contacts']['hosts'], $matches[1]);
            }
            elseif (preg_match("/Warning: Service '(.+)' on host '(.+)' has no default contacts or contactgroups defined!/", $line, $matches)) {
                $key = preg_replace("/\W+/", "_", strtolower($matches[1]));
                $key = trim($key, "_");
                if ((!isset($results['services_without_contacts'][$key])) || (!is_array($results['services_without_contacts'][$key]))) {
                    ++$results['services_without_contacts']['count'];
                    $results['services_without_contacts'][$key] = array();
                    $results['services_without_contacts'][$key]['count'] = 0;
                    $results['services_without_contacts'][$key]['hosts'] = array();
                }
                ++$results['services_without_contacts'][$key]['count'];
                array_push($results['services_without_contacts'][$key]['hosts'], $matches[2]);
            }
        }
        RevDeploy::setConsumerDeploymentInfo($deployment, false, 'hostaudit', $results);
        unset($testReturn, $buildReturn);
    }
    return;
}

/**
 * verifyBuild 
 * 
 * @param mixed $deployment    deployment we are building for verification purposes
 * @param mixed $revision      revision we are building for verification purposes
 *
 * @access public
 * @return void
 */
function verifyBuild($deployment, $revision)
{
    $buildReturn = NagCreate::buildDeployment($deployment, $revision, false, true, false);
    if ($buildReturn !== true) {
        Chat::messageByDeployment($deployment, "Verification Build: Failed to build configs for Deployment: $deployment", 'red', true);
        unset($buildReturn);
    }
    else {
        $testReturn = NagCreate::testDeployment($deployment);
        if ($testReturn['exitcode'] != 0) {
            Chat::messageByDeployment($deployment, "Verification Build: Configs failed to test properly for Deployment: $deployment", 'red', true);
        }
        unset($testReturn, $buildReturn);
    }
    return;
}

/**
 * Envoke Signal Handling function
 */
$run = true;
pcntl_signal(SIGTERM, "sighandler");
pcntl_signal(SIGQUIT, "sighandler");
pcntl_signal(SIGINT, "sighandler");
pcntl_signal(SIGQUIT, "sighandler");
pcntl_signal(SIGABRT, "sighandler");
/**
 * Write PID File
 */
file_put_contents(PIDFILE, getmypid());
/**
 * Initialize Beanstalkd Connection
 */
NagPhean::init(BEANSTALKD_SERVER, BEANSTALKD_TUBE, true);
/**
 * While Main Loop
 */
while ($run) {
    $job = NagPhean::reserveJob();
    $data = $job->getData();
    $jsonObj = json_decode($data);
    if ($jsonObj->type == 'test') {
        $lockReturn =
            RevDeploy::createConsumerDeploymentLock(
                $jsonObj->deployment, $jsonObj->revision, 'test'
            );
        if ($lockReturn !== false) {
            testBuild($jsonObj->deployment, $jsonObj->revision, $jsonObj->shard);
            NagPhean::delJob($job);
            RevDeploy::deleteConsumerDeploymentLock(
                $jsonObj->deployment, $jsonObj->revision, 'test'
            );
        }
        unset($lockReturn);
    }
    elseif ($jsonObj->type == 'build') {
        $lockReturn =
            RevDeploy::createConsumerDeploymentLock(
                $jsonObj->deployment, $jsonObj->revision, 'build'
            );
        if ($lockReturn !== false) {
            showBuild($jsonObj->deployment, $jsonObj->revision, $jsonObj->shard);
            NagPhean::delJob($job);
            RevDeploy::deleteConsumerDeploymentLock(
                $jsonObj->deployment, $jsonObj->revision, 'build'
            );
        }
        unset($lockReturn);
    }
    elseif ($jsonObj->type == 'diff') {
        $lockReturn =
            RevDeploy::createConsumerDeploymentLock($jsonObj->deployment, false, 'diff');
        if ($lockReturn !== false) {
            diffBuild($jsonObj->deployment, $jsonObj->fromrev, $jsonObj->torev, $jsonObj->shard);
            NagPhean::delJob($job);
            RevDeploy::deleteConsumerDeploymentLock($jsonObj->deployment, false, 'diff');
        }
    }
    elseif ($jsonObj->type == 'verify') {
        verifyBuild($jsonObj->deployment, $jsonObj->revision);
        NagPhean::delJob($job);
    }
    elseif ($jsonObj->type == 'hostaudit') {
        // Not setting a lock, since this is a background job and doesn't return directly too the user...
        hostaudit($jsonObj->deployment);
        NagPhean::delJob($job);
    }
    unset($job, $data, $jsonObj);
}

