#!/usr/bin/php -d hidef.data_path=no
<?php
/* Define Base Path */
define('BASE_PATH', '/opt/saigon');
/* Include Auto Loader */
require_once BASE_PATH.'/lib/classLoader.class.php';
Saigon_ClassLoader::register();

$rand = floor(mt_rand(0, 2));
$sleepRand = floor(mt_rand(15, 45));
if ($rand == 1) {
    $contents = "# Cronjob for Saigon Nagios Consumer Call Back Execution\n";
    $contents .= "00,15,30,45 * * * * root sleep $sleepRand; /opt/saigon/consumer/saigon-nagios-builder\n";
} elseif ( $rand == 2 ) {
    $contents = "# Cronjob for Saigon Nagios Consumer Call Back Execution\n";
    $contents .= "05,20,35,50 * * * * root sleep $sleepRand; /opt/saigon/consumer/saigon-nagios-builder\n";
} else {
    $contents = "# Cronjob for Saigon Nagios Consumer Call Back Execution\n";
    $contents .= "10,25,40,55 * * * * root sleep $sleepRand; /opt/saigon/consumer/saigon-nagios-builder\n";
}
$md5Contents = md5($contents);
FileUtils::writeFile('/etc/cron.d/saigon-nagios-builder', $contents, $md5Contents);

exit;
