<?php
//
// Copyright (c) 2013, Zynga Inc.
// https://github.com/zynga/saigon
// Author: Matt West (https://github.com/mhwest13)
// License: BSD 2-Clause
//

class NRPECreate
{

    const FILEHEADER = "# This file has been autogenerated, any changes you make to this file\n# will be overridden the next time the consumer runs\n\n";

    /**
     * buildNRPEFile 
     * 
     * @param mixed $deployment 
     * @param mixed $revision 
     * @param mixed $nrpeInfo 
     * @static
     * @access public
     * @return void
     */
    public static function buildNRPEFile($deployment, $revision, $nrpeInfo)
    {
        ksort($nrpeInfo);
        $filecontents = self::FILEHEADER;
        foreach($nrpeInfo as $key => $value) {
            if (($key == 'cmds') || ($key == 'location')) continue;
            $filecontents .= "$key=$value\n";
        }
        $filecontents .= "\n";
        $cmds = preg_split('/,/', $nrpeInfo['cmds']);
        $nrpecmdlines = self::buildNRPECmdLines($deployment, $revision, $cmds);
        $filecontents .= implode("\n", $nrpecmdlines);
        return $filecontents;
    }

    /**
     * buildSupNRPEFile 
     * 
     * @param mixed $deployment 
     * @param mixed $revision 
     * @param mixed $supnrpeInfo 
     * @static
     * @access public
     * @return void
     */
    public static function buildSupNRPEFile($deployment, $revision, $supnrpeInfo)
    {
        $cmds = preg_split('/,/', $supnrpeInfo['cmds']);
        $nrpecmdlines = self::buildNRPECmdLines($deployment, $revision, $cmds);
        $filecontents = self::FILEHEADER;
        $filecontents .= implode("\n", $nrpecmdlines);
        return $filecontents;
    }

    /**
     * buildNRPECmdLines 
     * 
     * @param mixed $deployment 
     * @param mixed $revision 
     * @param array $cherrypick 
     * @static
     * @access public
     * @return void
     */
    public static function buildNRPECmdLines($deployment, $revision, array $cherrypick = array())
    {
        $nrpecmds = RevDeploy::getCommonMergedDeploymentNRPECmds($deployment, $revision);
        if (!empty($nrpecmds)) {
            $results = array();
            if (empty($cherrypick)) {
                foreach ($nrpecmds as $nrpecmd => $nrpecmdInfo) {
                    $cmdline = "command[$nrpecmd]=" . base64_decode($nrpecmdInfo['cmd_line']);
                    $results[$nrpecmd] = $cmdline;
                }
            } else {
                foreach ($nrpecmds as $nrpecmd => $nrpecmdInfo) {
                    if (!in_array($nrpecmd, $cherrypick)) continue;
                    $cmdline = "command[$nrpecmd]=" . base64_decode($nrpecmdInfo['cmd_line']);
                    $results[$nrpecmd] = $cmdline;
                }
            }
            ksort($results);
            return $results;
        }
        return array();
    }

}

